---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lightsout.techsupport.mk
  resources:
  - lightsoutnamespaceschedules
  - lightsoutschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lightsout.techsupport.mk
  resources:
  - lightsoutnamespaceschedules/finalizers
  - lightsoutschedules/finalizers
  verbs:
  - update
- apiGroups:
  - lightsout.techsupport.mk
  resources:
  - lightsoutnamespaceschedules/status
  - lightsoutschedules/status
  verbs:
  - get
  - patch
  - update
