//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LightsOutSchedule) DeepCopyInto(out *LightsOutSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LightsOutSchedule.
func (in *LightsOutSchedule) DeepCopy() *LightsOutSchedule {
	if in == nil {
		return nil
	}
	out := new(LightsOutSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LightsOutSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LightsOutScheduleList) DeepCopyInto(out *LightsOutScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LightsOutSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LightsOutScheduleList.
func (in *LightsOutScheduleList) DeepCopy() *LightsOutScheduleList {
	if in == nil {
		return nil
	}
	out := new(LightsOutScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LightsOutScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LightsOutScheduleSpec) DeepCopyInto(out *LightsOutScheduleSpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WorkloadTypes != nil {
		in, out := &in.WorkloadTypes, &out.WorkloadTypes
		*out = make([]WorkloadType, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeLabels != nil {
		in, out := &in.ExcludeLabels, &out.ExcludeLabels
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.UpscaleRateLimit != nil {
		in, out := &in.UpscaleRateLimit, &out.UpscaleRateLimit
		*out = new(RateLimitConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DownscaleRateLimit != nil {
		in, out := &in.DownscaleRateLimit, &out.DownscaleRateLimit
		*out = new(RateLimitConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LightsOutScheduleSpec.
func (in *LightsOutScheduleSpec) DeepCopy() *LightsOutScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(LightsOutScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LightsOutScheduleStatus) DeepCopyInto(out *LightsOutScheduleStatus) {
	*out = *in
	if in.LastUpscaleTime != nil {
		in, out := &in.LastUpscaleTime, &out.LastUpscaleTime
		*out = (*in).DeepCopy()
	}
	if in.LastDownscaleTime != nil {
		in, out := &in.LastDownscaleTime, &out.LastDownscaleTime
		*out = (*in).DeepCopy()
	}
	if in.NextUpscaleTime != nil {
		in, out := &in.NextUpscaleTime, &out.NextUpscaleTime
		*out = (*in).DeepCopy()
	}
	if in.NextDownscaleTime != nil {
		in, out := &in.NextDownscaleTime, &out.NextDownscaleTime
		*out = (*in).DeepCopy()
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.WorkloadStats = in.WorkloadStats
	if in.ScalingProgress != nil {
		in, out := &in.ScalingProgress, &out.ScalingProgress
		*out = new(ScalingProgress)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LightsOutScheduleStatus.
func (in *LightsOutScheduleStatus) DeepCopy() *LightsOutScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(LightsOutScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitConfig) DeepCopyInto(out *RateLimitConfig) {
	*out = *in
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int)
		**out = **in
	}
	if in.DelayBetweenBatches != nil {
		in, out := &in.DelayBetweenBatches, &out.DelayBetweenBatches
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitConfig.
func (in *RateLimitConfig) DeepCopy() *RateLimitConfig {
	if in == nil {
		return nil
	}
	out := new(RateLimitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingProgress) DeepCopyInto(out *ScalingProgress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingProgress.
func (in *ScalingProgress) DeepCopy() *ScalingProgress {
	if in == nil {
		return nil
	}
	out := new(ScalingProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadStats) DeepCopyInto(out *WorkloadStats) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadStats.
func (in *WorkloadStats) DeepCopy() *WorkloadStats {
	if in == nil {
		return nil
	}
	out := new(WorkloadStats)
	in.DeepCopyInto(out)
	return out
}
